### PR TITLE
Fix the conflict between the custom "utils" and the pip package "utils"

### PR DESCRIPTION
**Pull request by Li-Jiaqi**
If we have installed the official package "utils" with pip, we should put "\path\to\dgd_person_reid"  in the front of the Python environment list. Then the custom package "\path\to\dgd_person_reid\utils" will be preferentially imported.

### CODE REVIEW

**Comment by Cysu** [comment]
Thank you very much for the pull request! And I apologize for the non-standard code that causes the issue.

Maybe we could consider a slightly better solution as below? For all the files of `data/*.py` and `tools/*.py`, let's change the header to

```python
from __future__ import absolute_import

from .utils import *    # actually it's quite bad to do so, will refactor it later
```

This will use the local module `utils` instead of the others installed by `pip`.

**Comment by Cysu** [comment]
Please refer to [PEP 328](https://www.python.org/dev/peps/pep-0328/#guido-s-decision).

**Comment by Li-Jiaqi** [comment]
Good idea! It's really a better solution~ And also don't forget `eval/metric_learning.py`

**Comment by Li-Jiaqi** [comment]
And also don't forget `eval/metric_learning.py`~~

**Comment by Cysu** [comment]
@Li-Jiaqi Why did you close this pull request? I was about to merge :)

Could you please move the `from __future__ import absolute_import` to the first line of each file? Thanks.

**Comment by Li-Jiaqi** [comment]
Maybe I have done some wrong operations because I'm not so familiar with git... 
Now I have updated the related 14 `*.py` files I have found ( `data/*.py` , `eval/*.py`, `tools/*.py` )

**Comment by Cysu** [comment]
My bad. Your original solution is correct. I have fixed it with several commits. Thank you so much!

**Pull request merged**
